Add support for sourcemaps
t32k/grunt-csso pull request #28
Opened 2016-11-15 15:55 UTC by szarouski

2016-11-16 01:21 UTC, nitriques commented
Hey @szarouski, this is great! But can you fix the build ? Right now, it's not working. See https://travis-ci.org/t32k/grunt-csso/jobs/176102824. You can run it locally before pushing, `npm run test`. Thanks!

2016-11-18 21:55 UTC, szarouski commented
Fixed. Don't know how I missed travis 😛

2016-11-27 18:33 UTC, szarouski commented
@nitriques does it look good now?

2016-12-14 21:13 UTC, nitriques requested changes

2016-12-14 21:13 UTC, nitriques commented on tasks/csso.js
> +        map = result.map || map;
The `|| map` is useless IMHO

2016-12-14 21:13 UTC, nitriques commented on tasks/csso.js
> +      if (css.length === 0) {
it would be better to do `!css`

2016-12-14 21:14 UTC, nitriques commented
Yes! Sorry @szarouski I was a lot busy in the past weeks. I've made another quick review: could you check it/argue with me/fix it ? Thanks!

2016-12-23 01:16 UTC, szarouski commented
@nitriques Thanks for review! 🍺 Updated.

2017-01-06 21:08 UTC, nitriques requested changes

2017-01-06 21:08 UTC, nitriques commented on tasks/csso.js
> +              grunt.log.write('File ' + chalk.cyan(mapDest) + ' created' + (options.report ? ': ' : '.'));
One last thing ! Both writes could happen in parallel with `fs.writeFile`. If you do not want to do it, just tell me ;)

2017-01-12 01:36 UTC, nitriques commented on tasks/csso.js
> +              grunt.log.write('File ' + chalk.cyan(mapDest) + ' created' + (options.report ? ': ' : '.'));
@szarouski ping!

2017-01-12 02:00 UTC, szarouski commented on tasks/csso.js
> +              grunt.log.write('File ' + chalk.cyan(mapDest) + ' created' + (options.report ? ': ' : '.'));
@nitriques Hey, I didn't forget, just didn't have time yet. I'll look into that during weekend :)

2017-01-13 22:20 UTC, nitriques commented on tasks/csso.js
> +              grunt.log.write('File ' + chalk.cyan(mapDest) + ' created' + (options.report ? ': ' : '.'));
Ok great ! Ping me if you have any questions. 
If you can't do it, I'll merge as is and do it ;) Thanks again!!!

2017-01-14 03:43 UTC, szarouski commented on test/csso-test.js
> +      fs.readFileSync('test/expected/sourcemap.css.map', 'utf8').replace(/(\\r)?\\n/g, eol === '\r\n' ? '\\r\\n' : '\\n'),
Had to write those replacements due to the way how sourcemaps are generated. Hacky but tests pass on windows, so i hope it is not a big deal.

2017-01-15 20:09 UTC, nitriques commented on test/csso-test.js
> +      fs.readFileSync('test/expected/sourcemap.css.map', 'utf8').replace(/(\\r)?\\n/g, eol === '\r\n' ? '\\r\\n' : '\\n'),
Yeah I'll try to create a better solution ;) Not a problem right now ;) Maybe force EOL to LF in tests...

2017-01-15 20:09 UTC, nitriques approved these changes

2017-01-15 20:11 UTC, merged

2017-01-15 22:11 UTC, nitriques commented
@szarouski Thanks! Check out the attached commits I've just pushed ;) And please test on Windows !

2017-01-16 00:53 UTC, szarouski commented
@nitriques, checked out latest version from `dev` tests are failing on windows for sourcemap:
```
Running "nodeunit:tests" (nodeunit) task
Testing csso-test.js.FF......
>> csso - sourcemap
>> Message: should create sourcemap
>> Error: '.a{-webkit-fi1ter:blur(5px);filter:blur(5px)}.b{-webkit-padding-before:10px;pad
ding-block-start:10px}\r\n/*# sourceMappingURL=sourcemap.css.map */' == '.a{-webkit-fi1ter
:blur(5px);filter:blur(5px)}.b{-webkit-padding-before:10px;padding-block-start:10px}\n/*#
sourceMappingURL=sourcemap.css.map */'
>>   at Object.sourcemap (test\csso-test.js:20:10)
>>   at runCallback (timers.js:574:20)
>>   at tryOnImmediate (timers.js:554:5)
>>   at processImmediate [as _immediateCallback] (timers.js:533:5)

>> csso - sourcemap
>> Message: should create sourcemap
>> Error: '{"version":3,"sources":["<unknown>"],"names":[],"mappings":"AAAA,E,CACC,wB,CACA
,gB,CAED,E,CACC,2B,CACA,wB","file":"<unknown>","sourcesContent":[".a {\\n\\t-webkit-fi1ter
: blur(5px);\\n\\tfilter: blur(5px);\\n}\\n.b {\\n\\t-webkit-padding-before: 10px;\\n\\tpa
dding-block-start: 10px;\\n}\\n\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZX
JzaW9uIjozLCJzb3VyY2VzIjpbInNvdXJjZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7SUFDSSww
QkFBa0I7WUFBbEIsa0JBQWtCO0NBQ3JCO0FBQ0Q7SUFDSSw2QkFBMEI7WUFBMUIsMEJBQTBCO0NBQzdCIiwiZmlsZS
I6InNvdXJjZS5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYSB7XG4gICAgZmlsdGVyOiBibHVyKDVweCk7XG59XG4u
YiB7XG4gICAgcGFkZGluZy1ibG9jay1zdGFydDogMTBweDtcbn1cbiJdfQ== */"]}' == '{"version":3,"sour
ces":["<unknown>"],"names":[],"mappings":"AAAA,E,CACC,wB,CACA,gB,CAED,E,CACC,2B,CACA,wB","
file":"<unknown>","sourcesContent":[".a {\\r\\n\\t-webkit-fi1ter: blur(5px);\\r\\n\\tfilte
r: blur(5px);\\r\\n}\\r\\n.b {\\r\\n\\t-webkit-padding-before: 10px;\\r\\n\\tpadding-block
-start: 10px;\\r\\n}\\r\\n\\r\\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJz
aW9uIjozLCJzb3VyY2VzIjpbInNvdXJjZS5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7SUFDSSwwQk
FBa0I7WUFBbEIsa0JBQWtCO0NBQ3JCO0FBQ0Q7SUFDSSw2QkFBMEI7WUFBMUIsMEJBQTBCO0NBQzdCIiwiZmlsZSI6
InNvdXJjZS5jc3MiLCJzb3VyY2VzQ29udGVudCI6WyIuYSB7XG4gICAgZmlsdGVyOiBibHVyKDVweCk7XG59XG4uYi
B7XG4gICAgcGFkZGluZy1ibG9jay1zdGFydDogMTBweDtcbn1cbiJdfQ== */"]}'
>>   at Object.sourcemap (test\csso-test.js:24:10)
>>   at runCallback (timers.js:574:20)
>>   at tryOnImmediate (timers.js:554:5)
>>   at processImmediate [as _immediateCallback] (timers.js:533:5)

>> csso - comments
>> Message: should minify and remove all but the first exclamation comment
>> Error: '.a{-webkit-fi1ter:blur(5px);filter:blur(5px)}.b{-webkit-padding-before:10px;pad
ding-block-start:10px}\r\n/*# sourceMappingURL=sourcemap.css.map */' == '.a{-webkit-fi1ter
:blur(5px);filter:blur(5px)}.b{-webkit-padding-before:10px;padding-block-start:10px}\n/*#
sourceMappingURL=sourcemap.css.map */'
>>   at Object.comments (test\csso-test.js:34:10)
>>   at runCallback (timers.js:574:20)
>>   at tryOnImmediate (timers.js:554:5)
>>   at processImmediate [as _immediateCallback] (timers.js:533:5)

Warning: 3/12 assertions failed (15ms) Use --force to continue.

```

2017-01-16 15:16 UTC, nitriques commented
Ok thanks. At home, I do not have a Windows machine (I've tested in on Ubuntu) but I do at work. Will test ASAP.

2017-01-16 20:14 UTC, nitriques commented
I have no problems running the test on my Windows machine.

I think it depends on your git config: if git converts LF to CRLF, then the test might not pass.

I've juste pushed a .gitattributes file to make sure your git config does not make the test fails.

2017-01-16 22:52 UTC, szarouski commented
I had an issue even after I pulled, so I decided to delete everything except for .git and try again. After reset everything works fine. Good job 👍